version: "3"
services:
  vahleim:
    build: .
    command: start Valheim --debug --verbose
    environment:
      SessionName: 'steamhydra-debug'
      ServerMap: 'mapname2'
      ServerPass: 'password3'
      # Port: 2456
      EnableMods: 'true'
      # Modloader: 'latest'
      Mods: ValheimArmory,EpicLoot,UseEquipmentInWater,Foraging,Lumberjacking,Ranching,SolidHitboxes,CreatureLevelAndLootControl,Endurance
      # Public: 'false'
    ports:
      - 2456:2456
      - 2456:2456/udp
      - 2457:2457
      - 2457:2457/udp
      - 2458:2458
      - 2458:2458/udp
    volumes:
      - server:/server
volumes:
  server: {}