version: "3"
services:
  vahleim:
    build: .
    command: start Valheim --debug --showstatus=false --update_mods_on_start=false
    environment:
      SessionName: 'steamhydra-debug'
      ServerMap: 'mapname2'
      ServerPass: 'password3'
      SaveInterval: 300
      # Port: 2456
      EnableMods: 'true'
      # Modloader: 'latest'
      # Mods: ValheimModding-Jotunn,MidnightMods-ValhimArmory
      # Public: 'false'
    ports:
      - 2456:2456
      - 2456:2456/udp
      - 2457:2457
      - 2457:2457/udp
      - 2458:2458
      - 2458:2458/udp
    volumes:
      - ./local-development-instance:/server/