version: "3"
services:
  vahleim:
    build: .
    command: start Valheim --debug --verbose
    environment:
      SessionName: 'session1'
      ServerMap: 'mapname2'
      ServerPass: 'password3'
      # Port: 2456
      EnableMods: 'true'
      # Modloader: '5.4.11' # newer versions are incompatible with Valheim
      # Public: 'false'
    ports:
      - 2456:2456
      - 2456:2456/udp
      - 2457:2457
      - 2457:2457/udp
      - 2458:2458
      - 2458:2458/udp
    volumes:
      - server:/server
volumes:
  server: {}